apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  DB_USER: a2V5Y2xvYWtfdXNlcg==  # keycloak_user
  DB_PASSWORD: a2V5Y2xvYWtfcGFzc3dvcmQ=  # keycloak_password
  KEYCLOAK_USER: YWRtaW4=  # admin
  KEYCLOAK_PASSWORD: YWRtaW5fcGFzc3dvcmQ=  # admin_password
