apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  DB_VENDOR: "MYSQL"
  DB_ADDR: "172.28.174.197"
  DB_PORT: "3306"
  DB_DATABASE: "keycloak"
  JDBC_PARAMS: "connectTimeout=30000"